<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>60e194d0-a69c-4541-99b1-56f8d1509d2e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PersonalWebCore\PersonalWebCore.csproj" />
    <ProjectReference Include="..\PersonalWebInfrastructure\PersonalWebInfrastructure.csproj" />
  </ItemGroup>

</Project>
